services:
  # Base de datos PostgreSQL
  - type: pserv
    name: postgresql-db
    env: docker
    image: postgres:15
    plan: free
    disk:
      name: postgres_data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    envVars:
      - key: POSTGRES_DB
        value: consultorio_odontologico_db
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: elkin
      - key: PGDATA
        value: /var/lib/postgresql/data/pgdata
    autoDeploy: true

  # Backend Spring Boot
  - type: web
    name: backend-app
    env: docker
    dockerfilePath: ./backend/Backend/Dockerfile
    dockerContext: ./backend/Backend
    plan: free
    envVars:
      - key: BD_URL
        value: jdbc:postgresql://postgresql-db:5432/consultorio_odontologico_db
      - key: BD_USER_NAME
        value: postgres
      - key: PASSWORD
        value: elkin
      - key: BD_DRIVER
        value: org.postgresql.Driver
      - key: KEY_SECRETS
        value: uPifhWrNRf7QEVv989LmBKfxEgdVeHlQGq+lQyC8ThuUYXBa8e0Yg0+tmkhAA/CpFv245Q9XGlorSP+ztihl/w==
      - key: EXPIRATIONS
        value: "86400000"
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: HIBERNATE_DDL_AUTO
        value: update
    autoDeploy: true

  # Frontend React/Vite
  - type: web
    name: frontend-app
    env: docker
    dockerfilePath: ./frontend/Frontend/Dockerfile
    dockerContext: ./frontend/Frontend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://backend-app.onrender.com
    autoDeploy: true