databases:
  # Base de datos PostgreSQL nativa de Render
  - name: consultorio-odontologico-db
    databaseName: consultorio_odontologico_db
    user: consultorio_odontologico_db
    plan: free

services:
  # Backend Spring Boot
  - type: web
    name: backend-app
    env: docker
    dockerfilePath: ./backend/Backend/Dockerfile
    dockerContext: ./backend/Backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: consultorio-odontologico-db
          property: connectionString
      - key: BD_URL
        fromDatabase:
          name: consultorio-odontologico-db
          property: connectionString
      - key: BD_USER_NAME
        fromDatabase:
          name: consultorio-odontologico-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: consultorio-odontologico-db
          property: password
      - key: BD_DRIVER
        value: org.postgresql.Driver
      - key: KEY_SECRETS
        value: uPifhWrNRf7QEVv989LmBKfxEgdVeHlQGq+lQyC8ThuUYXBa8e0Yg0+tmkhAA/CpFv245Q9XGlorSP+ztihl/w==
      - key: EXPIRATIONS
        value: "86400000"
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: HIBERNATE_DDL_AUTO
        value: update
    autoDeploy: true

  # Frontend React/Vite
  - type: web
    name: frontend-app
    env: docker
    dockerfilePath: ./frontend/Frontend/Dockerfile
    dockerContext: ./frontend/Frontend
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://backend-app.onrender.com
    autoDeploy: true